name: Publish Docker Images

on:
  push:
    tags:
      - '**'

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: rockstorm/gitweb
        tags: |
          # production (i.e. 2.36+b1)
          type=ref,event=tag,priority=600
          # stable (i.e. 2.36)
          type=match,pattern=[^\+]+,priority=500

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: 'rockstorm'
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: |
          linux/386
          linux/amd64
          linux/arm/v6
          linux/arm/v7
          linux/arm64/v8
          linux/ppc64le
          linux/s390x
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
